### ISSUE TITLE
Crashes in Environment with Unadopted Cameras

### ISSUE THREAD

**Issue by BREC-IT** [terafin/mqtt-unifi-protect-bridge#101]
In the pollBootstrap function, defining the constant name causes an exception when camera name is _null_. This occurs in environments where there are cameras that haven't been adopted or where cameras are adopted by another controller. In our usage, I threw in a conditional using **camera.isAdopted**, which results in as expected functionality.

**Comment by terafin** [comment]
Thanks!

**Comment by terafin** [comment]
Should be fixed with https://github.com/terafin/mqtt-unifi-protect-bridge/commit/c1aab3b62a9b497b243e57264e55b7c2b65be521

Docker image should auto push in 5 mins or so
